// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Ndx_TvqDloVFkrpnvrmBMwnymox0Mdo',
    appId: '1:472313211101:web:6b3c26f9e3d85c17de5334',
    messagingSenderId: '472313211101',
    projectId: 'vibe-9a579',
    authDomain: 'vibe-9a579.firebaseapp.com',
    storageBucket: 'vibe-9a579.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzfaMV_sUAZHCqCF8ZNr8rqvTu37suyoU',
    appId: '1:472313211101:android:7792871d9d8d045fde5334',
    messagingSenderId: '472313211101',
    projectId: 'vibe-9a579',
    storageBucket: 'vibe-9a579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBckeVx34Qb-L_lZt2DAQtenvhfCNQUIac',
    appId: '1:472313211101:ios:cd158c7f3ffe8f2bde5334',
    messagingSenderId: '472313211101',
    projectId: 'vibe-9a579',
    storageBucket: 'vibe-9a579.appspot.com',
    iosClientId: '472313211101-o8d3rk5de6f0hlni66bjmfb39a1oapfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBckeVx34Qb-L_lZt2DAQtenvhfCNQUIac',
    appId: '1:472313211101:ios:cd158c7f3ffe8f2bde5334',
    messagingSenderId: '472313211101',
    projectId: 'vibe-9a579',
    storageBucket: 'vibe-9a579.appspot.com',
    iosClientId: '472313211101-o8d3rk5de6f0hlni66bjmfb39a1oapfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab',
  );
}
