// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRf2c4HKsMtT3xi2vUa5hE037P-3XjZO0',
    appId: '1:230453938887:web:704b602200fe7c36904ce2',
    messagingSenderId: '230453938887',
    projectId: 'aghaobeidat-fa2b5',
    authDomain: 'aghaobeidat-fa2b5.firebaseapp.com',
    storageBucket: 'aghaobeidat-fa2b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHr2PaVIBnFeQwABe_Hf_tLxpXRH0Caho',
    appId: '1:230453938887:android:fa15c85c2d7f1abb904ce2',
    messagingSenderId: '230453938887',
    projectId: 'aghaobeidat-fa2b5',
    storageBucket: 'aghaobeidat-fa2b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmlNAAoMAGlCdmHkQZjiQTD3UKKrMtqlk',
    appId: '1:230453938887:ios:712101a539891ed2904ce2',
    messagingSenderId: '230453938887',
    projectId: 'aghaobeidat-fa2b5',
    storageBucket: 'aghaobeidat-fa2b5.appspot.com',
    iosClientId: '230453938887-rgg91pd9s7qjb5e5qb96sco8vd66625n.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmlNAAoMAGlCdmHkQZjiQTD3UKKrMtqlk',
    appId: '1:230453938887:ios:712101a539891ed2904ce2',
    messagingSenderId: '230453938887',
    projectId: 'aghaobeidat-fa2b5',
    storageBucket: 'aghaobeidat-fa2b5.appspot.com',
    iosClientId: '230453938887-rgg91pd9s7qjb5e5qb96sco8vd66625n.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab',
  );
}
